name: Generate Terraform README docs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read


jobs:
  docs:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@7f8a667921aee9dd89af0f3c6dfa6160d7ebd8bb # v1.4.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
