name: "Format Code: ensure code formatting guidelines are met"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: write
  security-events: write  # needed for SARIF upload

jobs:
  format-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Format Code Action
        uses: ministryofjustice/modernisation-platform-github-actions/format-code@66f68a92282f387d7026f435d4519fd1487cf44a
        with:
          ignore_files: "README.md"

      - name: Run Signed Commit Action
        uses: ministryofjustice/modernisation-platform-github-actions/signed-commit@66f68a92282f387d7026f435d4519fd1487cf44a
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "GitHub Actions Code Formatter workflow"
          pr_body: "This pull request includes updates from the GitHub Actions Code Formatter workflow. Please review the changes and merge if everything looks good."
